version: "3"
services:
  postgres:
    image: mypostgres:latest
    #build: ./sql/
    network_mode: bridge
    #container_name: postgres
    expose:
    - 5433
    ports:
      - 5433:5432
    volumes:
         - pgdata:/var/lib/postgresql/data    
    environment:
         - POSTGRES_PASSWORD=password
         - POSTGRES_USER=postgres
         - POSTGRES_DB=testdb
    restart: unless-stopped
# APP*****************************************
  app:
    image: mywebapp:latest
    network_mode: bridge
    #container_name: springbootapp
    expose:
      - 8080
    ports:
      - 8080:8080
    restart: unless-stopped
    depends_on:
      - postgres
    links:
      - postgres
volumes:
  pgdata:
